OPERATORS = [
    # ── Luxury-fit operators (luxury_fit_score 4-5) ─────────────────────────────

    {
        "id": "access_nepal_tours_trekking",
        "name": "Access Nepal Tours & Trekking",
        "destinations": ["Nepal", "Everest Region", "Kathmandu", "Annapurna"],
        "styles": ["luxury", "comfort", "adventure", "trekking"],
        "hotel_rating": 4.5,
        "price_per_day": 348,
        "location": "Thamel / Amrit Marga, Kathmandu, Nepal",
        "verified": True,
        "featured": True,
        "rating": 4.9,
        "reviews": 287,
        "bookings": 634,
        "specialties": [
            "Everest Base Camp Luxury Trek",
            "Luxury lodge upgrades",
            "Helicopter-supported trekking",
            "Kathmandu boutique hotel stays",
            "Private guiding",
        ],
        "description": (
            "One of Nepal's strongest luxury-fit operators. Access Nepal specialises in "
            "premium Everest and Annapurna experiences with deluxe teahouses, luxury lodge "
            "options, helicopter-supported segments, and high-end Kathmandu accommodation. "
            "Their EBC Luxury Trek is consistently rated the best in class."
        ),
        "website": "https://accessnepaltour.com",
        "email": "info@accessnepaltour.com",
        "whatsapp": "+977-9841021636",
        "telegram_handle": "@access_nepal",
        "image_color": "bg-emerald-100",
        "cover_image": "/operators/access_nepal_tours_trekking.jpg",
        "packages": [
            {
                "id": "pkg_access_1",
                "name": "Everest Base Camp Luxury Trek",
                "duration": 14,
                "price_per_day": 264,
                "total_price": 3690,
                "difficulty": "Strenuous",
                "max_group": 8,
                "type": "Group",
                "refundable": True,
                "deposit_required": True,
                "featured": True,
                "includes": [
                    "Private certified guide",
                    "Deluxe teahouse & luxury lodge accommodation",
                    "All meals (trail + Kathmandu)",
                    "Permits & park fees",
                    "Emergency helicopter insurance",
                    "Kathmandu boutique hotel (2 nights)",
                ],
                "excludes": ["International flights", "Personal gear", "Tips"],
                "cancellation_policy": "Fully refundable until 30 days before departure",
                "daily_breakdown": [
                    {"label": "Days 1–2 (Kathmandu)", "price": 220},
                    {"label": "Days 3–8 (Trek in)", "price": 270},
                    {"label": "Days 9–11 (EBC & surrounds)", "price": 290},
                    {"label": "Days 12–14 (Return)", "price": 250},
                ],
                "taxes_fees": 443,
                "discount_label": "Luxury lodge upgrades included",
            },
            {
                "id": "pkg_access_2",
                "name": "Kathmandu Luxury + Everest Heli Tour",
                "duration": 7,
                "price_per_day": 613,
                "total_price": 4290,
                "difficulty": "Easy",
                "max_group": 4,
                "type": "Private",
                "refundable": False,
                "deposit_required": True,
                "featured": False,
                "includes": [
                    "Private guide throughout",
                    "5-star Kathmandu hotel",
                    "Helicopter to Everest Base Camp and return",
                    "All meals",
                    "Cultural day tours",
                    "Permits & transfers",
                ],
                "excludes": ["International flights", "Visas", "Tips"],
                "cancellation_policy": "Non-refundable — helicopter slots committed 14 days out",
                "daily_breakdown": [
                    {"label": "Days 1–3 (Kathmandu cultural)", "price": 450},
                    {"label": "Day 4 (Heli to EBC & return)", "price": 1200},
                    {"label": "Days 5–7 (Pokhara + return)", "price": 480},
                ],
                "taxes_fees": 515,
                "discount_label": "",
            },
        ],
        "negotiation_script": {
            "opening": "Namaste! For the 7-day Everest creator route you've described, we quote $348/person/day — Kathmandu boutique hotel, deluxe teahouses, private guide, permits, and heli exit Day 6 blended into that average.",
            "counter_1": "For a confirmed group with social reach, we can move to $328/day and add a dedicated camera porter plus Pasang as lead guide.",
            "counter_2": "$308/day is our floor for this inclusion set at this group size — heli window firming by Day 5.",
            "accept": "Confirmed at $308/day — all inclusions locked. We'll send the personal briefs today.",
        },
    },

    {
        "id": "hiking_nepal",
        "name": "Hiking Nepal",
        "destinations": ["Nepal", "Everest Region", "Annapurna", "Pikey Peak", "Tibet", "Bhutan"],
        "styles": ["luxury", "adventure", "trekking", "cultural"],
        "hotel_rating": 4.0,
        "price_per_day": 200,
        "location": "Dabali Marga, Thamel, Kathmandu",
        "verified": True,
        "featured": True,
        "rating": 4.8,
        "reviews": 214,
        "bookings": 521,
        "specialties": [
            "Pikey Peak Luxury Trek",
            "Heated lodge network",
            "En-suite teahouse upgrades",
            "Solar-heated water on route",
            "Helicopter return options",
        ],
        "description": (
            "Hiking Nepal is the go-to for luxury-lite Himalayan trekking, especially on Pikey Peak "
            "and lower Solukhumbu alternatives. Their upgraded lodge network features electric blankets, "
            "en-suite bathrooms, solar-heated water, and satellite Wi-Fi at key stops."
        ),
        "website": "https://www.hikingnepal.com",
        "email": "info@hikingnepal.com",
        "whatsapp": "+977-9802342081",
        "telegram_handle": "@hiking_nepal",
        "image_color": "bg-teal-100",
        "cover_image": "/operators/hiking_nepal.jpg",
        "packages": [
            {
                "id": "pkg_hikn_1",
                "name": "Pikey Peak Luxury Trek",
                "duration": 7,
                "price_per_day": 200,
                "total_price": 1400,
                "difficulty": "Moderate",
                "max_group": 10,
                "type": "Group",
                "refundable": True,
                "deposit_required": True,
                "featured": True,
                "includes": [
                    "Certified guide",
                    "Heated en-suite lodge upgrades",
                    "Electric blankets & solar-heated water",
                    "All meals",
                    "Permits",
                ],
                "excludes": ["International flights", "Personal gear", "Tips"],
                "cancellation_policy": "Fully refundable until 21 days before departure",
                "daily_breakdown": [
                    {"label": "Days 1–2 (Kathmandu & drive)", "price": 160},
                    {"label": "Days 3–5 (Pikey Peak trek)", "price": 220},
                    {"label": "Days 6–7 (Return)", "price": 180},
                ],
                "taxes_fees": 168,
                "discount_label": "Satellite Wi-Fi included",
            },
            {
                "id": "pkg_hikn_2",
                "name": "Everest Luxury Trek — Full Route",
                "duration": 14,
                "price_per_day": 218,
                "total_price": 3050,
                "difficulty": "Strenuous",
                "max_group": 8,
                "type": "Group",
                "refundable": True,
                "deposit_required": True,
                "featured": False,
                "includes": [
                    "Private guide",
                    "Upgraded lodge network",
                    "All meals",
                    "Permits & park fees",
                    "Porter (1 per 2 pax)",
                ],
                "excludes": ["Flights to Lukla", "Personal gear"],
                "cancellation_policy": "Refundable until 30 days before departure",
                "daily_breakdown": [
                    {"label": "Days 1–4 (Kathmandu + Phakding)", "price": 190},
                    {"label": "Days 5–10 (EBC approach)", "price": 235},
                    {"label": "Days 11–14 (Return)", "price": 210},
                ],
                "taxes_fees": 366,
                "discount_label": "",
            },
        ],
        "negotiation_script": {
            "opening": "Namaste! For your 7-day luxury creator trek, we'd start at $175/day — heated lodges, guide, all meals, permits, and en-suite upgrades throughout.",
            "counter_1": "For a group with content reach, $150/day works. We'll add satellite Wi-Fi access at each lodge and a porter for camera gear.",
            "counter_2": "Final offer: $130/day. That's our break-even on this route with the luxury lodge upgrades. Can't go lower without cutting inclusions.",
            "accept": "Deal at $130/day. Guide confirmed, lodges pre-booked. Welcome to Pikey Peak!",
        },
    },

    {
        "id": "nepal_vision_treks_expeditions",
        "name": "Nepal Vision Treks & Expeditions",
        "destinations": ["Nepal", "Everest Region", "Annapurna Region", "Upper Mustang", "Langtang", "Tibet"],
        "styles": ["luxury", "adventure", "trekking", "cultural"],
        "hotel_rating": 4.0,
        "price_per_day": 227,
        "location": "Thamel, Kathmandu, Nepal",
        "verified": True,
        "featured": True,
        "rating": 4.8,
        "reviews": 178,
        "bookings": 413,
        "specialties": [
            "Everest Luxury Lodge Trek",
            "Helicopter-supported trekking",
            "Upper Mustang restricted zone",
            "Multi-country expeditions",
            "Luxury teahouse network",
        ],
        "description": (
            "Nepal Vision offers a strong portfolio of Everest luxury and lodge products including "
            "helicopter-assisted routes and the exclusive Everest Luxury Lodge Trek. Good fit for "
            "Everest luxury/lodge positioning and heli-style comfort. Upper Mustang specialist."
        ),
        "website": "https://www.nepalvisiontreks.com",
        "email": "info@nepalvisiontreks.com",
        "whatsapp": "+977-9802342081",
        "telegram_handle": "@nepal_vision",
        "image_color": "bg-indigo-100",
        "cover_image": "/operators/nepal_vision_treks_expeditions.jpg",
        "packages": [
            {
                "id": "pkg_nv_1",
                "name": "Everest Luxury Lodge Trek",
                "duration": 14,
                "price_per_day": 277,
                "total_price": 3880,
                "difficulty": "Strenuous",
                "max_group": 6,
                "type": "Private",
                "refundable": True,
                "deposit_required": True,
                "featured": True,
                "includes": [
                    "Private guide & porter",
                    "Luxury lodge accommodation throughout",
                    "All meals",
                    "Permits & fees",
                    "Kathmandu hotel (pre & post)",
                ],
                "excludes": ["International flights", "Personal gear", "Tips"],
                "cancellation_policy": "Fully refundable until 30 days before departure",
                "daily_breakdown": [
                    {"label": "Days 1–2 (Kathmandu)", "price": 200},
                    {"label": "Days 3–10 (EBC route)", "price": 290},
                    {"label": "Days 11–14 (Return)", "price": 260},
                ],
                "taxes_fees": 466,
                "discount_label": "Luxury lodge throughout",
            },
            {
                "id": "pkg_nv_2",
                "name": "Everest Luxury Trek — Classic",
                "duration": 14,
                "price_per_day": 227,
                "total_price": 3180,
                "difficulty": "Strenuous",
                "max_group": 10,
                "type": "Group",
                "refundable": True,
                "deposit_required": True,
                "featured": False,
                "includes": [
                    "Certified guide",
                    "Teahouse/lodge mix",
                    "All meals",
                    "Permits",
                ],
                "excludes": ["Flights to Lukla", "Personal gear"],
                "cancellation_policy": "Refundable until 21 days before departure",
                "daily_breakdown": [
                    {"label": "Days 1–4 (Kathmandu + approach)", "price": 190},
                    {"label": "Days 5–11 (EBC)", "price": 250},
                    {"label": "Days 12–14 (Return)", "price": 220},
                ],
                "taxes_fees": 382,
                "discount_label": "",
            },
        ],
        "negotiation_script": {
            "opening": "Namaste! The Everest Luxury Lodge Trek is $227/day — lodge accommodation throughout, guide, porter, meals, and permits. What group size are you planning?",
            "counter_1": "For an influencer booking with content rights, we can move to $195/day and include a Upper Mustang village stop as a bonus day.",
            "counter_2": "Last call: $175/day. Lodge upgrades stay, meals stay, guide stays. Cannot compromise on safety costs.",
            "accept": "Confirmed at $175/day. We'll lock the lodges today. Excellent itinerary!",
        },
    },

    {
        "id": "amigo_treks",
        "name": "Amigo Treks",
        "destinations": ["Nepal", "Everest Region", "Annapurna Region", "Langtang Region", "Tibet", "Bhutan"],
        "styles": ["luxury", "custom", "trekking", "cultural", "helicopter"],
        "hotel_rating": 4.0,
        "price_per_day": 175,
        "location": "Amrit Marga, Thamel, Kathmandu, Nepal",
        "verified": True,
        "featured": True,
        "rating": 4.7,
        "reviews": 156,
        "bookings": 342,
        "specialties": [
            "Luxury Everest Base Camp",
            "Ultimate Luxury Kathmandu",
            "Helicopter tours",
            "Private custom journeys",
            "Hotel & lodge planning",
        ],
        "description": (
            "Amigo Treks is positioned around luxury access and private journeys. "
            "Their newer site explicitly markets custom itineraries, private hotels, "
            "helicopter-supported routes, and transfers. Strong fit for bespoke influencer trips."
        ),
        "website": "https://www.amigotreks.com.np",
        "email": "info@amigotrekking.com",
        "whatsapp": "+977-9851136878",
        "telegram_handle": "@amigo_treks",
        "image_color": "bg-violet-100",
        "cover_image": "/operators/amigo_treks.jpg",
        "packages": [
            {
                "id": "pkg_amg_1",
                "name": "Luxury Everest Base Camp — Private",
                "duration": 12,
                "price_per_day": 175,
                "total_price": 2100,
                "difficulty": "Strenuous",
                "max_group": 4,
                "type": "Private",
                "refundable": True,
                "deposit_required": True,
                "featured": True,
                "includes": [
                    "Private guide",
                    "Luxury & helicopter-supported route",
                    "Custom hotel & lodge selection",
                    "All meals",
                    "Permits & transfers",
                ],
                "excludes": ["International flights", "Personal insurance", "Tips"],
                "cancellation_policy": "Fully refundable until 30 days before departure",
                "daily_breakdown": [
                    {"label": "Days 1–3 (Kathmandu)", "price": 150},
                    {"label": "Days 4–9 (EBC route)", "price": 190},
                    {"label": "Days 10–12 (Return)", "price": 160},
                ],
                "taxes_fees": 252,
                "discount_label": "Fully private",
            },
            {
                "id": "pkg_amg_2",
                "name": "Everest Base Camp Trek + Gokyo Lake",
                "duration": 14,
                "price_per_day": 126,
                "total_price": 1770,
                "difficulty": "Strenuous",
                "max_group": 12,
                "type": "Group",
                "refundable": True,
                "deposit_required": False,
                "featured": False,
                "includes": [
                    "Certified guide",
                    "Teahouse accommodation",
                    "All meals",
                    "Permits",
                    "Gokyo Lake extension",
                ],
                "excludes": ["Flights", "Personal gear"],
                "cancellation_policy": "Refundable until 14 days before departure",
                "daily_breakdown": [
                    {"label": "Days 1–4 (Approach)", "price": 110},
                    {"label": "Days 5–11 (EBC + Gokyo)", "price": 140},
                    {"label": "Days 12–14 (Return)", "price": 115},
                ],
                "taxes_fees": 212,
                "discount_label": "",
            },
        ],
        "negotiation_script": {
            "opening": "Hey! For a custom private luxury trek with helicopter support, we're looking at $175/day — full custom route, private guide, and hotel/lodge selection handled for you.",
            "counter_1": "For content creator trips with tagging, $150/day. We'll create a bespoke itinerary with your shot list built in.",
            "counter_2": "Absolute lowest for the private + helicopter option: $135/day. We lose margin but get the exposure.",
            "accept": "Done at $135/day! Custom brief incoming. Let's build something special.",
        },
    },

    {
        "id": "himalayan_ecstasy_nepal",
        "name": "Himalayan Ecstasy Nepal",
        "destinations": ["Nepal", "Everest Region", "Kanchenjunga", "Himalaya", "Trekking regions"],
        "styles": ["adventure", "trekking", "climbing", "private/custom"],
        "hotel_rating": 4.0,
        "price_per_day": 180,
        "location": "Chaksibari Marg, Thamel, Kathmandu, Nepal",
        "verified": True,
        "featured": True,
        "rating": 4.8,
        "reviews": 134,
        "bookings": 298,
        "specialties": [
            "Private & custom expeditions",
            "High-altitude climbing",
            "Kanchenjunga treks",
            "Everest summit support",
            "Expert Sherpa guiding",
        ],
        "description": (
            "Himalayan Ecstasy is founded and led by experienced Himalayan guides including an "
            "Everest summiteer. Specialises in private, high-touch expeditions and custom trips "
            "with deep guide expertise. Strong for adventurous influencer content."
        ),
        "website": "https://himalayanecstasynepal.com",
        "email": "info@himalayanecstasynepal.com",
        "whatsapp": "+977-9801126622",
        "telegram_handle": "@himalayan_ecstasy",
        "image_color": "bg-sky-100",
        "cover_image": "/operators/himalayan_ecstasy_nepal.jpg",
        "packages": [
            {
                "id": "pkg_he_1",
                "name": "Custom Private Himalaya Expedition",
                "duration": 10,
                "price_per_day": 180,
                "total_price": 1800,
                "difficulty": "Strenuous",
                "max_group": 4,
                "type": "Private",
                "refundable": True,
                "deposit_required": True,
                "featured": True,
                "includes": [
                    "Expert Sherpa guide (summiteer)",
                    "Custom route planning",
                    "Best available lodging on route",
                    "All meals",
                    "Permits & safety equipment",
                ],
                "excludes": ["International flights", "Personal gear", "Tips"],
                "cancellation_policy": "Fully refundable until 21 days before departure",
                "daily_breakdown": [
                    {"label": "Days 1–2 (Kathmandu)", "price": 150},
                    {"label": "Days 3–8 (Expedition route)", "price": 195},
                    {"label": "Days 9–10 (Return)", "price": 160},
                ],
                "taxes_fees": 216,
                "discount_label": "Expert guide team",
            },
            {
                "id": "pkg_he_2",
                "name": "Everest Classic Trek — Expert Led",
                "duration": 14,
                "price_per_day": 155,
                "total_price": 2170,
                "difficulty": "Strenuous",
                "max_group": 8,
                "type": "Group",
                "refundable": True,
                "deposit_required": True,
                "featured": False,
                "includes": [
                    "Expert guide",
                    "Teahouse accommodation",
                    "All meals",
                    "Permits",
                ],
                "excludes": ["Flights", "Personal gear"],
                "cancellation_policy": "Refundable until 21 days before departure",
                "daily_breakdown": [
                    {"label": "Days 1–4 (Approach)", "price": 130},
                    {"label": "Days 5–11 (EBC route)", "price": 170},
                    {"label": "Days 12–14 (Return)", "price": 145},
                ],
                "taxes_fees": 260,
                "discount_label": "",
            },
        ],
        "negotiation_script": {
            "opening": "Hello! For your private custom trek with expert guide, we start at $180/day. Anil (Everest summiteer) would personally lead the expedition.",
            "counter_1": "For an influencer trip with content value, $155/day and we'll adapt the route to your shot list.",
            "counter_2": "Final: $140/day with Anil as lead guide. This is below market for this calibre of expertise.",
            "accept": "Confirmed at $140/day. Anil is booked. This will be extraordinary!",
        },
    },

    # ── Mid-range operators (luxury_fit_score 3) ─────────────────────────────────

    {
        "id": "treks_planner_nepal",
        "name": "Treks Planner Nepal",
        "destinations": ["Nepal", "Everest Region", "Annapurna", "Langtang", "Tibet", "Bhutan"],
        "styles": ["adventure", "custom", "trekking", "heli tour"],
        "hotel_rating": 3.5,
        "price_per_day": 140,
        "location": "Keshar Mahal Road, Thamel, Kathmandu",
        "verified": True,
        "featured": False,
        "rating": 4.6,
        "reviews": 122,
        "bookings": 274,
        "specialties": [
            "Helicopter tours (Everest & Annapurna)",
            "Customizable packages",
            "Everest panoramic heli-sightseeing",
            "Multi-country itineraries",
        ],
        "description": (
            "Treks Planner Nepal excels in flexible, helicopter-heavy itineraries and "
            "customizable packages across Nepal, Tibet, and Bhutan. Good for clients who want "
            "to see the Himalayas from the air as well as on foot."
        ),
        "website": "https://www.treksplannernepal.com",
        "email": "info@treksplannernepal.com",
        "whatsapp": "+977-9810334042",
        "telegram_handle": "@treks_planner",
        "image_color": "bg-cyan-100",
        "cover_image": "/operators/treks_planner_nepal.jpg",
        "packages": [
            {
                "id": "pkg_tp_1",
                "name": "Everest Panoramic Heli-Sightseeing",
                "duration": 1,
                "price_per_day": 1495,
                "total_price": 1495,
                "difficulty": "Easy",
                "max_group": 5,
                "type": "Private",
                "refundable": True,
                "deposit_required": False,
                "featured": True,
                "includes": [
                    "Private helicopter",
                    "Pilot + guide",
                    "Everest flyover + EBC landing",
                    "Breakfast at hotel",
                ],
                "excludes": ["Hotel accommodation", "Insurance"],
                "cancellation_policy": "Refundable 72 hours before (weather dependent)",
                "daily_breakdown": [
                    {"label": "Full day heli tour", "price": 1495},
                ],
                "taxes_fees": 179,
                "discount_label": "Weather guarantee reschedule",
            },
            {
                "id": "pkg_tp_2",
                "name": "Everest Base Camp Trek — Customizable",
                "duration": 14,
                "price_per_day": 100,
                "total_price": 1400,
                "difficulty": "Strenuous",
                "max_group": 14,
                "type": "Group",
                "refundable": True,
                "deposit_required": False,
                "featured": False,
                "includes": [
                    "Guide",
                    "Teahouse accommodation",
                    "Breakfast & dinner",
                    "Permits",
                ],
                "excludes": ["Flights", "Lunch", "Personal gear"],
                "cancellation_policy": "Fully refundable until 14 days before departure",
                "daily_breakdown": [
                    {"label": "Days 1–4 (Approach)", "price": 90},
                    {"label": "Days 5–11 (EBC route)", "price": 110},
                    {"label": "Days 12–14 (Return)", "price": 90},
                ],
                "taxes_fees": 168,
                "discount_label": "",
            },
        ],
        "negotiation_script": {
            "opening": "Hi! For a customized Nepal trek with helicopter add-on, we start at $140/day. Helicopter segments are priced separately per flight.",
            "counter_1": "For a group with social reach, $120/day and we include one complimentary heli-sightseeing flight.",
            "counter_2": "Final: $105/day with the heli flight included. That's our limit.",
            "accept": "Great, $105/day with helicopter flight confirmed!",
        },
    },

    {
        "id": "himalayan_adventure_nepal",
        "name": "Himalayan Adventure Nepal (HAN)",
        "destinations": ["Nepal", "Everest Region", "Annapurna", "Tibet", "Bhutan"],
        "styles": ["adventure", "trekking", "cultural", "custom"],
        "hotel_rating": 3.5,
        "price_per_day": 115,
        "location": "Bhagwan Bahal, Kathmandu, Nepal",
        "verified": True,
        "featured": False,
        "rating": 4.7,
        "reviews": 98,
        "bookings": 201,
        "specialties": [
            "Everest Base Camp",
            "Annapurna Base Camp",
            "Cultural tours",
            "Custom trekking",
            "Multi-country itineraries",
        ],
        "description": (
            "Experienced operator since the early 1990s. Himalayan Adventure Nepal has deep "
            "route knowledge across Everest, Annapurna, and cultural destinations. "
            "Good for reliable, experienced guiding on classic routes."
        ),
        "website": "https://www.himalayanadventurenepal.com",
        "email": "info@himalayanadventurenepal.com",
        "whatsapp": "+977-9851099397",
        "telegram_handle": "@han_trekking",
        "image_color": "bg-amber-100",
        "cover_image": "/operators/himalayan_adventure_nepal.jpg",
        "packages": [
            {
                "id": "pkg_han_1",
                "name": "Everest Base Camp Trek — Classic",
                "duration": 14,
                "price_per_day": 115,
                "total_price": 1610,
                "difficulty": "Strenuous",
                "max_group": 12,
                "type": "Group",
                "refundable": True,
                "deposit_required": True,
                "featured": True,
                "includes": [
                    "Certified guide",
                    "Teahouse accommodation",
                    "All meals on trail",
                    "Permits & park fees",
                ],
                "excludes": ["Flights to Lukla", "Personal gear", "Tips"],
                "cancellation_policy": "Refundable until 21 days before departure",
                "daily_breakdown": [
                    {"label": "Days 1–4 (Approach)", "price": 100},
                    {"label": "Days 5–11 (EBC route)", "price": 125},
                    {"label": "Days 12–14 (Return)", "price": 105},
                ],
                "taxes_fees": 193,
                "discount_label": "",
            },
            {
                "id": "pkg_han_2",
                "name": "Annapurna Base Camp Trek",
                "duration": 12,
                "price_per_day": 110,
                "total_price": 1320,
                "difficulty": "Moderate",
                "max_group": 14,
                "type": "Group",
                "refundable": True,
                "deposit_required": False,
                "featured": False,
                "includes": ["Guide", "Teahouse accommodation", "All meals", "Permits"],
                "excludes": ["Flights to Pokhara", "Gear"],
                "cancellation_policy": "Refundable until 14 days before departure",
                "daily_breakdown": [
                    {"label": "Days 1–3 (Pokhara & entry)", "price": 95},
                    {"label": "Days 4–9 (ABC route)", "price": 120},
                    {"label": "Days 10–12 (Return)", "price": 100},
                ],
                "taxes_fees": 158,
                "discount_label": "",
            },
        ],
        "negotiation_script": {
            "opening": "Namaste! Classic EBC trek runs $115/day — guide, teahouses, meals, permits all in.",
            "counter_1": "For a group, $100/day and we add an acclimatization day tour at Namche.",
            "counter_2": "Best we can do: $90/day. Full inclusions stay.",
            "accept": "Confirmed at $90/day. Experienced guide and full classic route!",
        },
    },

    {
        "id": "adventure_mountain_explore",
        "name": "Adventure Mountain Explore (AME)",
        "destinations": ["Nepal", "Tibet", "Bhutan"],
        "styles": ["adventure", "trekking", "custom"],
        "hotel_rating": 3.5,
        "price_per_day": 120,
        "location": "Thamel, Kathmandu, Nepal",
        "verified": True,
        "featured": False,
        "rating": 4.6,
        "reviews": 89,
        "bookings": 186,
        "specialties": [
            "Everest Base Camp Trek",
            "Annapurna Circuit",
            "Tibet tours",
            "Bhutan custom tours",
            "Travel logistics",
        ],
        "description": (
            "AME is a local trekking and expedition operator with broad travel logistics "
            "capability including accommodation, air tickets, and multi-country tours. "
            "Founded and led by experienced Himalayan guides."
        ),
        "website": "https://www.ametreks.com",
        "email": "info@ametreks.com",
        "whatsapp": "+977-9767556118",
        "telegram_handle": "@ame_treks",
        "image_color": "bg-orange-100",
        "cover_image": "/operators/adventure_mountain_explore.jpg",
        "packages": [
            {
                "id": "pkg_ame_1",
                "name": "Everest Base Camp Trek",
                "duration": 14,
                "price_per_day": 120,
                "total_price": 1680,
                "difficulty": "Strenuous",
                "max_group": 12,
                "type": "Group",
                "refundable": True,
                "deposit_required": True,
                "featured": True,
                "includes": ["Guide", "Teahouse accommodation", "All meals", "Permits"],
                "excludes": ["Flights", "Personal gear"],
                "cancellation_policy": "Refundable until 21 days before departure",
                "daily_breakdown": [
                    {"label": "Days 1–4 (Approach)", "price": 105},
                    {"label": "Days 5–11 (EBC)", "price": 130},
                    {"label": "Days 12–14 (Return)", "price": 110},
                ],
                "taxes_fees": 202,
                "discount_label": "",
            },
            {
                "id": "pkg_ame_2",
                "name": "Annapurna Circuit Trek",
                "duration": 14,
                "price_per_day": 110,
                "total_price": 1540,
                "difficulty": "Strenuous",
                "max_group": 14,
                "type": "Group",
                "refundable": True,
                "deposit_required": False,
                "featured": False,
                "includes": ["Guide", "Teahouse stays", "All meals", "Permits"],
                "excludes": ["Flights", "Gear"],
                "cancellation_policy": "Refundable until 14 days before",
                "daily_breakdown": [
                    {"label": "Days 1–4 (Entry)", "price": 95},
                    {"label": "Days 5–11 (Circuit)", "price": 120},
                    {"label": "Days 12–14 (Return)", "price": 100},
                ],
                "taxes_fees": 185,
                "discount_label": "",
            },
        ],
        "negotiation_script": {
            "opening": "Hi! EBC trek runs $120/day — guide, accommodation, meals, permits included.",
            "counter_1": "For a group, $105/day. We can arrange extra porter support.",
            "counter_2": "Minimum: $95/day with full inclusions.",
            "accept": "Confirmed at $95/day. Great trek ahead!",
        },
    },

    {
        "id": "caravan_outdoors",
        "name": "Caravan Outdoors",
        "destinations": ["Nepal", "India", "Tibet", "Bhutan"],
        "styles": ["adventure", "trekking", "custom"],
        "hotel_rating": 3.5,
        "price_per_day": 115,
        "location": "Bhagawan Bahal, Thamel, Kathmandu, Nepal",
        "verified": True,
        "featured": False,
        "rating": 4.6,
        "reviews": 76,
        "bookings": 163,
        "specialties": [
            "Nepal trekking",
            "Bhutan tours",
            "Peak climbing",
            "Expeditions",
            "Multi-country travel",
        ],
        "description": (
            "Caravan Outdoors is an experienced outdoor team (50+ trips) offering quality "
            "trekking, peak climbing, and multi-country adventures across Nepal, India, "
            "Tibet, and Bhutan. Emphasis on safety and experienced team leadership."
        ),
        "website": "https://caravanoutdoors.com",
        "email": "info@caravanoutdoors.com",
        "whatsapp": "+977-9851049483",
        "telegram_handle": "@caravan_outdoors",
        "image_color": "bg-lime-100",
        "cover_image": "/operators/caravan_outdoors.jpg",
        "packages": [
            {
                "id": "pkg_co_1",
                "name": "Nepal Trekking — Custom",
                "duration": 10,
                "price_per_day": 115,
                "total_price": 1150,
                "difficulty": "Moderate",
                "max_group": 12,
                "type": "Group",
                "refundable": True,
                "deposit_required": False,
                "featured": True,
                "includes": ["Guide", "Teahouse accommodation", "All meals", "Permits"],
                "excludes": ["Flights", "Personal gear"],
                "cancellation_policy": "Refundable until 14 days before",
                "daily_breakdown": [
                    {"label": "Days 1–3 (Kathmandu)", "price": 100},
                    {"label": "Days 4–8 (Trek)", "price": 125},
                    {"label": "Days 9–10 (Return)", "price": 100},
                ],
                "taxes_fees": 138,
                "discount_label": "",
            },
        ],
        "negotiation_script": {
            "opening": "Namaste! Custom Nepal trek runs $115/day — guide, accommodation, meals, all permits included.",
            "counter_1": "Group rate: $100/day with porter support added.",
            "counter_2": "Final offer: $90/day. Full inclusions stay.",
            "accept": "Confirmed at $90/day. Good trekking ahead!",
        },
    },

    {
        "id": "nepal_peak_adventure",
        "name": "Nepal Peak Adventure",
        "destinations": ["Nepal", "Everest Region", "Annapurna Region", "Langtang", "Manaslu", "Dolpo"],
        "styles": ["adventure", "peak climbing", "trekking", "budget-friendly"],
        "hotel_rating": 3.5,
        "price_per_day": 110,
        "location": "Bhagwan Bahal Street, Thamel, Kathmandu, Nepal",
        "verified": True,
        "featured": False,
        "rating": 4.7,
        "reviews": 92,
        "bookings": 218,
        "specialties": [
            "Annapurna Circuit Trek",
            "Manaslu Circuit Trek",
            "Island Peak climbing",
            "Mera Peak climbing",
            "Remote region trekking",
        ],
        "description": (
            "Nepal Peak Adventure is a trekking and peak-climbing specialist led by professional "
            "guide Hom Rana. Covers all major trekking regions plus remote areas like Dolpo and "
            "Manaslu. Offers budget, luxury, and classic trip options."
        ),
        "website": "https://nepalpeakadventure.com",
        "email": "info@nepalpeakadventure.com",
        "whatsapp": "+977-9841319155",
        "telegram_handle": "@nepal_peak",
        "image_color": "bg-rose-100",
        "cover_image": "/operators/nepal_peak_adventure.jpg",
        "packages": [
            {
                "id": "pkg_npa_1",
                "name": "Mera Peak Climbing",
                "duration": 18,
                "price_per_day": 144,
                "total_price": 2590,
                "difficulty": "Strenuous",
                "max_group": 8,
                "type": "Group",
                "refundable": True,
                "deposit_required": True,
                "featured": True,
                "includes": [
                    "Certified climbing guide",
                    "Climbing permits",
                    "All equipment",
                    "Teahouse + base camp accommodation",
                    "All meals",
                ],
                "excludes": ["International flights", "Personal gear", "Tips"],
                "cancellation_policy": "Refundable until 30 days before departure",
                "daily_breakdown": [
                    {"label": "Days 1–5 (Approach)", "price": 110},
                    {"label": "Days 6–12 (Acclimatization)", "price": 130},
                    {"label": "Days 13–15 (Summit push)", "price": 200},
                    {"label": "Days 16–18 (Return)", "price": 110},
                ],
                "taxes_fees": 311,
                "discount_label": "Climbing gear included",
            },
            {
                "id": "pkg_npa_2",
                "name": "Annapurna Circuit Trek",
                "duration": 14,
                "price_per_day": 99,
                "total_price": 1380,
                "difficulty": "Strenuous",
                "max_group": 14,
                "type": "Group",
                "refundable": True,
                "deposit_required": False,
                "featured": False,
                "includes": ["Guide", "Teahouse accommodation", "All meals", "Permits"],
                "excludes": ["Flights to Pokhara", "Personal gear"],
                "cancellation_policy": "Refundable until 14 days before",
                "daily_breakdown": [
                    {"label": "Days 1–4 (Entry)", "price": 85},
                    {"label": "Days 5–11 (Circuit)", "price": 108},
                    {"label": "Days 12–14 (Return)", "price": 90},
                ],
                "taxes_fees": 166,
                "discount_label": "",
            },
        ],
        "negotiation_script": {
            "opening": "Hi! Annapurna Circuit starts at $110/day — guide, teahouses, meals, permits.",
            "counter_1": "Group rate: $95/day.",
            "counter_2": "Final: $85/day. Cannot go lower.",
            "accept": "Deal at $85/day!",
        },
    },

    # ── Budget-to-mid operators (luxury_fit_score 2-2.5) ────────────────────────

    {
        "id": "classic_outdoors",
        "name": "Classic Outdoors",
        "destinations": ["Nepal", "India", "Tibet", "Bhutan"],
        "styles": ["adventure", "trekking", "custom", "heli tour"],
        "hotel_rating": 3.0,
        "price_per_day": 100,
        "location": "Jyatha, Thamel, Kathmandu, Nepal",
        "verified": True,
        "featured": False,
        "rating": 4.5,
        "reviews": 88,
        "bookings": 197,
        "specialties": [
            "Everest Base Camp Trek",
            "Helicopter tours",
            "Annapurna Sanctuary Trek",
            "Manaslu Circuit Trek",
            "Mountain biking",
        ],
        "description": (
            "Classic Outdoors offers a broad range of Nepal trekking, helicopter tours, and "
            "adventure activities across Nepal, India, Tibet, and Bhutan. Good general operator "
            "for standard trekking and heli packages."
        ),
        "website": "https://www.classicoutdoors.com.np",
        "email": "info@theclassicoutdoors.com",
        "telegram_handle": "@classic_outdoors",
        "image_color": "bg-stone-100",
        "cover_image": "/operators/classic_outdoors.jpg",
        "packages": [
            {
                "id": "pkg_cl_1",
                "name": "Everest Base Camp Trek",
                "duration": 14,
                "price_per_day": 99,
                "total_price": 1390,
                "difficulty": "Strenuous",
                "max_group": 16,
                "type": "Group",
                "refundable": True,
                "deposit_required": False,
                "featured": True,
                "includes": ["Guide", "Mountain lodge accommodation", "Meals", "Permits"],
                "excludes": ["Flights", "Personal gear"],
                "cancellation_policy": "Fully refundable until 14 days before",
                "daily_breakdown": [
                    {"label": "Days 1–4 (Approach)", "price": 90},
                    {"label": "Days 5–11 (EBC route)", "price": 108},
                    {"label": "Days 12–14 (Return)", "price": 90},
                ],
                "taxes_fees": 167,
                "discount_label": "",
            },
        ],
        "negotiation_script": {
            "opening": "Hello! EBC trek is $100/day all-in.",
            "counter_1": "Group discount: $88/day.",
            "counter_2": "Final: $80/day.",
            "accept": "Confirmed at $80/day!",
        },
    },

    {
        "id": "imperial_nepal_treks",
        "name": "Imperial Nepal Treks",
        "destinations": ["Nepal", "Everest Region", "Annapurna Region", "Langtang", "Upper Mustang", "Tibet", "Bhutan"],
        "styles": ["budget-friendly", "comfort", "trekking", "local expert"],
        "hotel_rating": 3.0,
        "price_per_day": 95,
        "location": "Dabali Marga, Thamel, Kathmandu, Nepal",
        "verified": True,
        "featured": False,
        "rating": 4.5,
        "reviews": 103,
        "bookings": 229,
        "specialties": [
            "Everest Base Camp Trek",
            "Everest View Luxury Lodge Trek",
            "Helicopter tours",
            "Annapurna Base Camp",
            "Upper Mustang",
        ],
        "description": (
            "Imperial Nepal Treks covers a wide inventory including a Everest View Luxury Lodge "
            "Trek and helicopter options alongside classic budget-friendly routes. "
            "Strong contactability with multiple WhatsApp numbers."
        ),
        "website": "https://www.imperialnepaltreks.com",
        "whatsapp": "+977-9851053103",
        "telegram_handle": "@imperial_nepal",
        "image_color": "bg-yellow-100",
        "cover_image": "/operators/imperial_nepal_treks.jpg",
        "packages": [
            {
                "id": "pkg_im_1",
                "name": "Classic Everest Base Camp",
                "duration": 14,
                "price_per_day": 89,
                "total_price": 1250,
                "difficulty": "Strenuous",
                "max_group": 16,
                "type": "Group",
                "refundable": True,
                "deposit_required": False,
                "featured": True,
                "includes": ["Guide", "Teahouse accommodation", "Meals", "Permits"],
                "excludes": ["Flights", "Gear"],
                "cancellation_policy": "Refundable until 14 days before",
                "daily_breakdown": [
                    {"label": "Days 1–4 (Approach)", "price": 80},
                    {"label": "Days 5–11 (EBC route)", "price": 97},
                    {"label": "Days 12–14 (Return)", "price": 80},
                ],
                "taxes_fees": 150,
                "discount_label": "",
            },
        ],
        "negotiation_script": {
            "opening": "Namaste! Classic EBC at $95/day all-in.",
            "counter_1": "Group discount: $82/day.",
            "counter_2": "Final: $75/day.",
            "accept": "Confirmed at $75/day!",
        },
    },

    {
        "id": "amazing_nepal_treks",
        "name": "Amazing Nepal Treks",
        "destinations": ["Nepal", "India", "Tibet", "Bhutan"],
        "styles": ["adventure", "trekking", "custom", "budget-friendly"],
        "hotel_rating": 3.0,
        "price_per_day": 80,
        "location": "Keshar Mahal Marg, Thamel, Kathmandu",
        "verified": True,
        "featured": False,
        "rating": 4.5,
        "reviews": 71,
        "bookings": 154,
        "specialties": [
            "Trekking packages",
            "Peak climbing",
            "Cultural travel",
            "Spiritual travel",
            "Safari & rafting",
        ],
        "description": (
            "Founded in 2017 by Santosh Adhikari and Nirmal Timilsina. Amazing Nepal Treks is "
            "a founder-led adventure operator strong on authentic trekking and multi-activity "
            "packages. Better positioned for adventure than luxury."
        ),
        "website": "https://www.amazingnepaltrek.com",
        "email": "info@amazingnepaltrek.com",
        "whatsapp": "+977-9851116042",
        "telegram_handle": "@amazing_nepal",
        "image_color": "bg-green-100",
        "cover_image": "/operators/amazing_nepal_treks.jpg",
        "packages": [
            {
                "id": "pkg_ant_1",
                "name": "Nepal Adventure Trek — Custom",
                "duration": 10,
                "price_per_day": 80,
                "total_price": 800,
                "difficulty": "Moderate",
                "max_group": 14,
                "type": "Group",
                "refundable": True,
                "deposit_required": False,
                "featured": True,
                "includes": ["Guide", "Teahouse accommodation", "Meals", "Permits"],
                "excludes": ["Flights", "Gear"],
                "cancellation_policy": "Refundable until 14 days before",
                "daily_breakdown": [
                    {"label": "Days 1–3 (Kathmandu)", "price": 70},
                    {"label": "Days 4–8 (Trek)", "price": 88},
                    {"label": "Days 9–10 (Return)", "price": 72},
                ],
                "taxes_fees": 96,
                "discount_label": "",
            },
        ],
        "negotiation_script": {
            "opening": "Hello! Custom adventure trek at $80/day — guide, accommodation, meals, permits.",
            "counter_1": "Group: $70/day.",
            "counter_2": "Final: $65/day.",
            "accept": "Confirmed at $65/day!",
        },
    },

    {
        "id": "aiming_adventure",
        "name": "Aiming Adventure",
        "destinations": ["Nepal", "Tibet", "Bhutan", "Everest", "Annapurna", "Langtang", "Mustang"],
        "styles": ["adventure", "trekking", "budget-friendly"],
        "hotel_rating": 3.0,
        "price_per_day": 90,
        "location": "Dabali Marga, Thamel, Kathmandu 44600",
        "verified": True,
        "featured": False,
        "rating": 4.5,
        "reviews": 64,
        "bookings": 138,
        "specialties": [
            "Everest Base Camp Trek",
            "Budget Annapurna Base Camp",
            "Gokyo Lake Trek",
            "Ghorepani Poon Hill Trek",
            "Peak climbing",
        ],
        "description": (
            "Aiming Adventure is a trekking and peak-climbing specialist with clear leadership "
            "(Bikal Duwadi, MD). Good for value-focused trekking across all major Nepal regions "
            "and into Tibet and Bhutan."
        ),
        "website": "https://www.aimingadventure.com",
        "email": "info@aimingadventure.com",
        "whatsapp": "+977-9849211457",
        "telegram_handle": "@aiming_adventure",
        "image_color": "bg-blue-100",
        "cover_image": "/operators/aiming_adventure.jpg",
        "packages": [
            {
                "id": "pkg_aim_1",
                "name": "Everest Base Camp Trek",
                "duration": 14,
                "price_per_day": 98,
                "total_price": 1365,
                "difficulty": "Strenuous",
                "max_group": 14,
                "type": "Group",
                "refundable": True,
                "deposit_required": False,
                "featured": True,
                "includes": ["Guide", "Teahouse accommodation", "Meals", "Permits"],
                "excludes": ["Flights", "Gear"],
                "cancellation_policy": "Refundable until 14 days before",
                "daily_breakdown": [
                    {"label": "Days 1–4 (Approach)", "price": 85},
                    {"label": "Days 5–11 (EBC route)", "price": 107},
                    {"label": "Days 12–14 (Return)", "price": 87},
                ],
                "taxes_fees": 164,
                "discount_label": "",
            },
            {
                "id": "pkg_aim_2",
                "name": "Budget Annapurna Base Camp Trek",
                "duration": 11,
                "price_per_day": 70,
                "total_price": 765,
                "difficulty": "Moderate",
                "max_group": 16,
                "type": "Group",
                "refundable": True,
                "deposit_required": False,
                "featured": False,
                "includes": ["Guide", "Teahouse", "Breakfast & dinner", "Permits"],
                "excludes": ["Flights", "Lunch", "Gear"],
                "cancellation_policy": "Refundable until 7 days before",
                "daily_breakdown": [
                    {"label": "Days 1–3 (Entry)", "price": 60},
                    {"label": "Days 4–8 (ABC route)", "price": 78},
                    {"label": "Days 9–11 (Return)", "price": 62},
                ],
                "taxes_fees": 92,
                "discount_label": "Budget-friendly",
            },
        ],
        "negotiation_script": {
            "opening": "Hi! EBC trek starts at $90/day all-in.",
            "counter_1": "Group: $78/day.",
            "counter_2": "Final: $70/day.",
            "accept": "Confirmed at $70/day!",
        },
    },

    {
        "id": "desire_adventure",
        "name": "Desire Adventure",
        "destinations": ["Nepal", "Tibet", "Bhutan", "Everest Region", "Annapurna Region", "Manaslu", "Upper Mustang"],
        "styles": ["budget-friendly", "adventure", "trekking", "custom"],
        "hotel_rating": 3.0,
        "price_per_day": 80,
        "location": "Chhaya Devi Complex, Thamel, Kathmandu, Nepal",
        "verified": True,
        "featured": False,
        "rating": 4.4,
        "reviews": 58,
        "bookings": 124,
        "specialties": [
            "Everest Base Camp Trek",
            "Pikey Peak Trek",
            "Short Manaslu Circuit",
            "Annapurna trekking packages",
            "Air ticketing",
        ],
        "description": (
            "Desire Adventure focuses on accessible pricing and affordable trekking packages. "
            "Strong on popular routes like EBC, Pikey Peak, and Annapurna. "
            "Good fit for budget-conscious groups and starter adventures."
        ),
        "website": "https://www.desireadventures.com",
        "email": "info@desirenepal.com",
        "telegram_handle": "@desire_adventure",
        "image_color": "bg-pink-100",
        "cover_image": "/operators/desire_adventure.jpg",
        "packages": [
            {
                "id": "pkg_da_1",
                "name": "Everest Base Camp Trek",
                "duration": 14,
                "price_per_day": 71,
                "total_price": 990,
                "difficulty": "Strenuous",
                "max_group": 16,
                "type": "Group",
                "refundable": True,
                "deposit_required": False,
                "featured": True,
                "includes": ["Guide", "Teahouse accommodation", "Meals", "Permits"],
                "excludes": ["Flights", "Gear"],
                "cancellation_policy": "Refundable until 14 days before",
                "daily_breakdown": [
                    {"label": "Days 1–4 (Approach)", "price": 62},
                    {"label": "Days 5–11 (EBC route)", "price": 78},
                    {"label": "Days 12–14 (Return)", "price": 63},
                ],
                "taxes_fees": 119,
                "discount_label": "Budget rate",
            },
            {
                "id": "pkg_da_2",
                "name": "Annapurna Trekking Package",
                "duration": 12,
                "price_per_day": 61,
                "total_price": 730,
                "difficulty": "Moderate",
                "max_group": 18,
                "type": "Group",
                "refundable": True,
                "deposit_required": False,
                "featured": False,
                "includes": ["Guide", "Teahouse", "Meals", "Permits"],
                "excludes": ["Flights", "Gear"],
                "cancellation_policy": "Refundable until 7 days before",
                "daily_breakdown": [
                    {"label": "Days 1–3 (Entry)", "price": 52},
                    {"label": "Days 4–9 (Annapurna route)", "price": 68},
                    {"label": "Days 10–12 (Return)", "price": 53},
                ],
                "taxes_fees": 88,
                "discount_label": "Best value",
            },
        ],
        "negotiation_script": {
            "opening": "Hi! EBC trek at $80/day — affordable, all-in.",
            "counter_1": "Group: $70/day.",
            "counter_2": "Final: $62/day.",
            "accept": "Confirmed at $62/day!",
        },
    },
]


def get_all_operators():
    return OPERATORS


def get_operator_by_id(op_id: str):
    for op in OPERATORS:
        if op["id"] == op_id:
            return op
    return None


def search_operators(destination: str, style: str, budget_per_day: float, hotel_rating: float):
    results = []
    dest_lower = destination.lower()
    style_lower = style.lower()

    for op in OPERATORS:
        score = 0
        dest_match = any(dest_lower in d.lower() or d.lower() in dest_lower for d in op["destinations"])
        if dest_match:
            score += 40
        style_match = any(style_lower in s.lower() or s.lower() in style_lower for s in op["styles"])
        if style_match:
            score += 30
        if op["price_per_day"] <= budget_per_day * 1.2:
            score += 20
        elif op["price_per_day"] <= budget_per_day * 1.5:
            score += 10
        rating_diff = abs(op["hotel_rating"] - hotel_rating)
        if rating_diff <= 0.5:
            score += 10
        elif rating_diff <= 1:
            score += 5

        if score > 0:
            op_copy = op.copy()
            op_copy["match_score"] = score
            if op["hotel_rating"] < hotel_rating:
                op_copy["constraint_note"] = (
                    f"Note: We can only offer {op['hotel_rating']}-star accommodation, "
                    f"not the {hotel_rating}-star you requested."
                )
            elif op["price_per_day"] > budget_per_day:
                op_copy["constraint_note"] = (
                    f"Note: Standard rate ${op['price_per_day']}/day exceeds your "
                    f"${int(budget_per_day)}/day budget. Negotiation possible."
                )
            results.append(op_copy)

    results.sort(key=lambda x: x["match_score"], reverse=True)
    return results[:4]
